---
title: "BitcoinPrice"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 
```{r currency historical data function}
library(stringr)
library(RCurl)
library(XML)
# List all coins
get_list_of_all_coinmarketcap_coins <- function() {
    url = 'https://coinmarketcap.com/all/views/all/'
    url_parsed <- htmlParse(getURL(url), asText = TRUE)
    tableNodes <- getNodeSet(url_parsed, c('//*[@id="currencies-all"]'))
    all_currency <- readHTMLTable(tableNodes[[1]])
    
    currencies <- gsub("\n","", all_currency$Name)
    
    currencies <- str_replace(gsub("\\s+", " ", str_trim(currencies)), "B", "b")
    
    c_symbols <- c()
    c_names <- c()
    
    for(c in currencies) {
        cr <- strsplit(c, " ")
        c_symbols <- c(c_symbols, cr[[1]][1])
        c_names <- c(c_names, cr[[1]][2])
    }
    
    cr_df <- cbind(c_names, c_symbols)
    colnames(cr_df) <- c('Name', 'Symbol')
    
    return(as.data.frame(cr_df))
}

# Function to create url from start to end
get_currency_data_download_url <- function(currency, history_start, history_end) {
  # Processing URL to download data
  url_cmarket <- 'https://coinmarketcap.com/'
  currency_part <- paste('currencies/', currency, sep="") 
  url_pre <- paste(url_cmarket, currency_part, sep="")

  # Append start date
  url_s <- paste(url_pre, '/historical-data/?start=', sep="")
  url_s <- paste(url_s, history_start, sep="") 

  # Append end date
  url_e <- paste(url_s, '&end=', sep="")
  url_e <- paste(url_e, history_end, sep="") 

  url <- url_e
}  

library(RCurl)
library(XML)
get_currency_historical_data <- function(url) {
  url_parsed <- htmlParse(getURL(url), asText = TRUE)
  print(url_parsed)
  tableNodes <- getNodeSet(url_parsed, c('//*[@class="table"]'))
  print(tableNodes)
  
  currency_historical_data <- readHTMLTable(tableNodes[[1]])
  
  return(currency_historical_data)
}                                         
```


```{r Bitcoin Historical Data from CoinMarketCap}
currency <- 'bitcoin'
history_start <- '20090101'
history_end <- format(Sys.time(), "%Y%m%d")

url <- get_currency_data_download_url(currency, history_start, history_end)

data <- get_currency_historical_data(url)
btc_data <- data

# Get the data
date <- as.Date(rev(data$Date), "%B %d, %Y")
price_high <- as.numeric(as.character(rev(data$High)))
price_low <- as.numeric(as.character(rev(data$Low)))
price_open <- as.numeric(as.character(rev(data$Open)))
price_close <- as.numeric(as.character(rev(data$Close)))
vol <- as.numeric(gsub(",", "", as.character(rev(data$Volume))))
vol[is.na(vol)] <- 0
mc <- as.numeric(gsub(",", "", as.character(rev(data$`Market Cap`))))
mc[is.na(mc)] <- 0


# plotting
library(plotly)
library(quantmod)

data$Date <- rev(date)
p <- data %>%
  plot_ly(x = ~Date, type="ohlc",
          open = ~Open, close = ~Close,
          high = ~High, low = ~Low) %>%
  layout(title = "Bitcoin Historical Price")

p


plot(date, price_high, cex=0.05)
lines(date, price_high)
lines(date, price_low, col='green')
points(date, price_low, col='green', cex=0.05)
lines(date, price_open, col='red')
points(date, price_open, col='red', cex=0.05)
lines(date, price_close, col='blue')
points(date, price_close, col='blue', cex=0.05)


```

```{r Historical Data from CoinMarketCap 1}
currency <- 'ethereum'
history_start <- '20090101'
history_end <- '20180130'

url <- get_currency_data_download_url(currency, history_start, history_end)

data <- get_currency_historical_data(url)
eth_data <- data

# Get the data
date <- as.Date(rev(data$Date), "%B %d, %Y")
price_high <- as.numeric(as.character(rev(data$High)))
price_low <- as.numeric(as.character(rev(data$Low)))
price_open <- as.numeric(as.character(rev(data$Open)))
price_close <- as.numeric(as.character(rev(data$Close)))
vol <- as.numeric(gsub(",", "", as.character(rev(data$Volume))))
vol[is.na(vol)] <- 0
mc <- as.numeric(gsub(",", "", as.character(rev(data$`Market Cap`))))
mc[is.na(mc)] <- 0


# plotting
library(plotly)
library(quantmod)
plot_title <- paste(currency, "Historical Price", sep=" ")

data$Date <- rev(date)
p <- data %>%
  plot_ly(x = ~Date, type="ohlc",
          open = ~Open, close = ~Close,
          high = ~High, low = ~Low) %>%
  layout(title = plot_title)

p

``` 


```{r}
library(plotly)

cur1_dat <- btc_data
cur2_dat <- eth_data
cur1_dat$Name <- 'BTC'
cur2_dat$Name <- 'ETH'

cur1_p_date <- as.Date(cur1_dat$Date, "%B %d, %Y")
cur2_p_date <- as.Date(cur2_dat$Date, "%B %d, %Y")

# Find the lowest timestamp to start
min_cur1_date <- min(cur1_p_date)
min_cur2_date <- min(cur2_p_date)
min_date <- max(min_cur1_date, min_cur2_date)

# Find the latest timestamp to end
max_cur1_date <- max(cur1_p_date)
max_cur2_date <- max(cur2_p_date)
max_date <- min(max_cur1_date, max_cur2_date)

cur1_s_id <- which(cur1_p_date == min_date)
cur1_e_ed <- which(cur1_p_date == max_date)

cur2_s_id <- which(cur2_p_date == min_date)
cur2_e_ed <- which(cur2_p_date == max_date)

# Create date sequence for x axis
x <- cur1_p_date[cur1_s_id:(cur1_e_ed + 1)]
n <- length(x) + 1
date <- as.character.Date(x)
dat1 <- cur1_dat[cur1_s_id:(cur1_e_ed + 1),]
dat2 <- cur2_dat[cur2_s_id:(cur2_e_ed + 1),]
y1_dat <- as.numeric(as.character(cur1_dat$Close[cur1_s_id:(cur1_e_ed + 1)]))
y2_dat <- as.numeric(as.character(cur2_dat$Close[cur2_s_id:(cur2_e_ed + 1)]))

createDualAxisPlot <- function(date, coin1, y1_dat, coin2, y2_dat) {
  trace1 <- list(
    x = c(date),
    y = c(y1_dat),
    line = list(color = "rgb(221, 42, 145)"), 
    marker = list(
      color = "rgb(0, 0, 155)", 
      size = 2
    ), 
    mode = "lines+markers", 
    name = coin1, 
    opacity = 1, 
    type = "scatter", 
    uid = "e27bd3", 
    xaxis = "x", 
    yaxis = "y" 
  )
  trace2 <- list(
    x = c(date),
    y = c(y2_dat), 
    line = list(color = "rgb(36, 32, 29)"), 
    marker = list(
      color = "rgb(228, 103, 9)", 
      size = 5
    ), 
    mode = "lines+markers", 
    name = coin2, 
    type = "scatter", 
    uid = "efd000", 
    yaxis = "y2" 
  )
  
  data <- list(trace1, trace2)

  layout <- list(
    autosize = TRUE, 
    hovermode = "closest", 
    showlegend = TRUE, 
    xaxis = list(
      autorange = TRUE, 
      #range = c(-0.745097129104, 11.4882190132), 
      title = "", 
      type = "date",
      showgrid = FALSE
    ), 
    yaxis = list(
      autorange = TRUE, 
      #domain = c(0, 1), 
      #range = c(-50, -20), 
      title = "USD", 
      type = "linear",
      showgrid = FALSE
    ), 
    yaxis2 = list(
      anchor = "x", 
      autorange = TRUE, 
      overlaying = "y", 
      #range = c(-25.3091876767, 55.9930010303), 
      title = "USD", 
      side = "right", 
      type = "linear",
      showgrid = FALSE,
      showline = TRUE
    )
  )


  p <- plot_ly()
  p <- add_trace(p, 
               x=trace1$x, 
               y=trace1$y, 
               line=trace1$line, 
               marker=trace1$marker, 
               mode=trace1$mode, 
               name=trace1$name, 
               opacity=trace1$opacity, 
               type=trace1$type, 
               uid=trace1$uid, 
               xaxis=trace1$xaxis, 
               yaxis=trace1$yaxis, 
               visible = TRUE 
               )
  p <- add_trace(p, 
               x=trace2$x, 
               y=trace2$y, 
               line=trace2$line, 
               marker=trace2$marker, 
               mode=trace2$mode, 
               name=trace2$name, 
               type=trace2$type, 
               uid=trace2$uid, 
               yaxis=trace2$yaxis, 
               visible = TRUE
               )
  p <- layout(p, 
            autosize=layout$autosize, 
            hovermode=layout$hovermode, 
            #showlegend=layout$showlegend, 
            xaxis=layout$xaxis, 
            yaxis=layout$yaxis, 
            yaxis2=layout$yaxis2
  )

  return(p)
}

p <- createDualAxisPlot(date, 'BTC', y1_dat, 'ETH', y2_dat)
p

#https://plot.ly/python/custom-buttons/  follow to finalize

```

```{r}
library(shiny)
library(mlbench)
library(plotly)
library(shinythemes)
library(dplyr)

numCoins = 15
currentCoinMetric = 'Close'
# Store features and actual class in seprate variables
if (exists("coin_info") == FALSE)
        coin_info <- get_list_of_all_coinmarketcap_coins()
if (exists("coin_data_lists") == FALSE)
    coin_data_lists <- list()
coins <- coin_info[1:numCoins,2] # First 15 coins
coinList <- as.character(coins)
coinNames <- as.character(coin_info[1:numCoins,1])
i <- 1
for (c in coinNames) {
   if (is.null(coin_data_lists[[coinList[i]]]) == TRUE) {
        url <- get_currency_data_download_url(c, history_start, history_end)
        coin_data_lists[[coinList[i]]] <- get_currency_historical_data(url)
   }
   i = i+1
}

coinMetrics <- c('Low', 'High', 'Open', 'Close', 'Volume', 'Market Cap')

# ui.R definition
ui <- fluidPage(
  # Set theme
  theme = shinytheme("spacelab"),

  # Feature selection
  fixedRow(
    column(4, selectInput(inputId = "coinInput1", label = "Select first coin", choices = coinList, selected = coinList[1])),
    column(4, selectInput(inputId = "coinInput2", label = "Select second coin", choices = coinList, selected = coinList[2])),
    column(4, selectInput(inputId = "coinMetric", label = "Select coin metric", choices = coinMetrics, selected = coinMetrics[1]))
    ),

  # First row
  fixedRow(
    column(12, plotlyOutput("Plot", height = "600px"))
    ,column(12, plotlyOutput("CorrelationPlot", height = "600px"))
    )
)

inputChangeEventHandler <- function(input, output) {
    # Create a convenience data.frame which can be used for charting
    coin1 <- input$coinInput1
    coin2 <- input$coinInput2
    
    history_start <- '20090101'
    history_end <- format(Sys.time(), "%Y%m%d")

    coin_data1 <- coin_data_lists[[coin1]]
    coin_data2 <- coin_data_lists[[coin2]]
    
    coin1_p_date <- as.Date(coin_data1$Date, "%B %d, %Y")
    coin2_p_date <- as.Date(coin_data2$Date, "%B %d, %Y")

    # Find the lowest timestamp to start
    min_coin1_date <- min(coin1_p_date)
    min_coin2_date <- min(coin2_p_date)
    min_date <- max(min_coin1_date, min_coin2_date)

    # Find the latest timestamp to end
    max_coin1_date <- max(coin1_p_date)
    max_coin2_date <- max(coin2_p_date)
    max_date <- min(max_coin1_date, max_coin2_date)

    coin1_s_id <- which(coin1_p_date == min_date)
    coin1_e_ed <- which(coin1_p_date == max_date)

    coin2_s_id <- which(coin2_p_date == min_date)
    coin2_e_ed <- which(coin2_p_date == max_date)

    # Create date sequence for x axis
    x <- coin1_p_date[coin1_s_id:(coin1_e_ed + 1)]
    n <- length(x) + 1
    date <- as.character.Date(x)
    dat1 <- coin_data1[coin1_s_id:(coin1_e_ed + 1),]
    dat2 <- coin_data2[coin2_s_id:(coin2_e_ed + 1),]
    
    date <- as.Date(as.character(dat1$Date) , "%b %d, %Y")
   
    if (input$coinMetric %in% c('Low', 'High', 'Open', 'Close')) 
    {  
        y1_dat <- as.numeric(as.character(dat1[, input$coinMetric]))
        y2_dat <- as.numeric(as.character(dat2[, input$coinMetric]))
    }
    else if (input$coinMetric %in% c('Market Cap', 'Volume')) {
       y1_dat <- as.numeric(as.character(gsub(",","",dat1[, input$coinMetric]))) 
       y2_dat <- as.numeric(as.character(gsub(",","",dat2[, input$coinMetric]))) 
    }
    
    ay <- list(
      #tickfont = list(color = "red"),
      overlaying = "y",
      side = "right"
    )
    p <- createDualAxisPlot(date, coin1, y1_dat, coin2, y2_dat)
    
    output$Plot <- renderPlotly({p})
}

# server
server <- function(input, output){
  # Observes the second feature input for a change
  observeEvent(input$coinMetric,{
      inputChangeEventHandler(input, output) 
  })
  observeEvent(input$coinInput1,{
      inputChangeEventHandler(input, output)
  })
  # Observes the second feature input for a change
  observeEvent(input$coinInput2,{
      inputChangeEventHandler(input, output)
  })
  
  # Coupled Correlation Plot on selection
  output$CorrelationPlot <- renderPlotly({

    # Get subset based on selection
    # event.data <- event_data("plotly_selected", source = "subset")
    # 
    # # If NULL dont do anything
    # if(is.null(event.data) == T) return(NULL)
    # 
    # # Get number of malignant and benign cases from selection
    # print(event.data)
    # curve_dat1 <- subset(event.data, curveNumber == 0)
    # curve_dat2 <- subset(event.data, curveNumber == 1)
    # print(curve_dat1)
    # print(curve_dat2)

    # Plot
    x_d <- seq(1,10)
    y_d <- seq(30,40)
    plot_ly(x = ~x_d, y = ~y_d, type = "scatter") %>%
      layout(title = "Correlation")
  })

}

runApp(shinyApp(ui, server), launch.browser=TRUE)


```

```{r coupled events}
library(shiny)
library(mlbench)
library(plotly)
library(shinythemes)
library(dplyr)

# Load data
data(BreastCancer)

# Remove NAs
BreastCancer <- na.omit(BreastCancer)

# Remvove ID
BreastCancer <- BreastCancer[,-1]

# Store features and actual class in seprate variables
featureList <- colnames(BreastCancer)[-10]
class <- BreastCancer$Class

# Convert to numeric
BreastCancer[,1:9] <- apply(BreastCancer[,-10], 2, as.numeric)

# ui.R definition
ui <- fluidPage(
  # Set theme
  theme = shinytheme("spacelab"),

  # Some help text
  h2("Coupled events in plotly charts using Shiny"),
  h4("This Shiny app showcases coupled events using Plotly's ", tags$code("event_data()"), " function."),
  tags$ol(
    tags$li("The first chart showcases", tags$code("plotly_selected")),
    tags$li("The third chart showcases", tags$code("plotly_click"))
  ),

  # Vertical space
  tags$hr(),

  # Feature selection
  fixedRow(
    column(6, selectInput(inputId = "featureInput1", label = "Select first feature", choices = featureList, selected = "Cell.Size")),
    column(6, selectInput(inputId = "featureInput2", label = "Select second feature (observed event)", choices = featureList, selected = "Epith.c.size"))),

  # First row
  fixedRow(
    column(6, plotlyOutput("Plot1", height = "600px")),
    column(6, plotlyOutput("Plot2", height = "600px"))),

  tags$hr(),
  tags$blockquote("First drag a selection box in the scatter plot to populate the barchart. Then select one of the bars in the barchat
    to populate the boxplot"),


  # Second row
  fixedRow(
    column(3, plotlyOutput("Plot3", height = "600px")),
    column(9, plotlyOutput("Plot4", height = "600px"))))

# server.R definition
server <- function(input, output){

  # Observes the second feature input for a change
  observeEvent(input$featureInput2,{

    # Create a convenience data.frame which can be used for charting
    plot.df <- data.frame(BreastCancer[,input$featureInput1],
                          BreastCancer[,input$featureInput2],
                          Class = BreastCancer$Class)

    # Add column names
    colnames(plot.df) <- c("x", "y", "Class")

    # Do a plotly contour plot to visualize the two featres with
    # the number of malignant cases as size
    # Note the use of 'source' argument
    output$Plot1 <- renderPlotly({
      plot_ly(plot.df, x = ~x, y = ~y, mode = "markers", type = "scatter", color = ~Class, source = "subset",
              marker = list(size = 30)) %>%
        layout(title = paste(input$featureInput1, "vs ", input$featureInput2),
               xaxis = list(title = input$featureInput1),
               yaxis = list(title = input$featureInput2),
               dragmode =  "select",
               plot_bgcolor = "6A446F")
    })

    # Create a contour plot of the number of malignant cases
    output$Plot2 <- renderPlotly({

      plot.df %>%
        group_by(x, y, Class) %>%
        summarize(Count = n()) %>%
        filter(Class == "malignant") %>%
        plot_ly(x = ~x, y = ~y, z = ~Count, type = "contour") %>%
        layout(title = "Contour map of number of malignant cases",
               xaxis = list(title = input$featureInput1),
               yaxis = list(title = input$featureInput2))

    })

    # Assign to parent environment
    plot.df <<- plot.df
  })

  # Coupled event 1
  output$Plot3 <- renderPlotly({

    # Get subset based on selection
    event.data <- event_data("plotly_selected", source = "subset")

    # If NULL dont do anything
    if(is.null(event.data) == T) return(NULL)

    # Get number of malignant and benign cases from selection
    malig.class <- subset(plot.df, Class == "malignant")[subset(event.data, curveNumber == 0)$pointNumber + 1,]
    benign.class <- subset(plot.df, Class == "benign")[subset(event.data, curveNumber == 1)$pointNumber + 1,]

    # Combine
    plot.subset <- rbind(malig.class, benign.class)

    # Summarize
    plot.summ <- plot.subset %>%
      group_by(x, y, Class) %>%
      summarize(Count = n())

    # Assign to parent frame
    plot.summ <<- plot.summ

    # Plot
    plot_ly(plot.summ, x = ~Class, y = ~Count, type = "bar", source = "select", color = ~Class) %>%
      layout(title = "No. of Malignant and Benign cases <br> in Selection",
             plot_bgcolor = "6A446F",
             yaxis = list(domain = c(0, 0.9)))
  })

  # Coupled event 2
  output$Plot4 <- renderPlotly({

    # Get subset based on selection
    event.data <- event_data("plotly_click", source = "select")

    # If NULL dont do anything
    if(is.null(event.data) == T) return(NULL)

    # If Malignant
    if(event.data[3] == "malignant"){

      tab <- subset(plot.summ, Class == "malignant")

      p1 <- plot_ly(tab, x = x, y = Count, type = "box", showlegend = F) %>%
        layout(yaxis = list(title = "Count"),
               xaxis = list(title = input$featureInput1))

      p2 <- plot_ly(tab, x = y, y = Count, type = "box", showlegend = F) %>%
        layout(title = "Box plot for Malignant cases",
               yaxis = list(title = "Count"),
               xaxis = list(title = input$featureInput2))

      subplot(p1, p2)
    }else{
      tab <- subset(plot.summ, Class == "benign")

      p1 <- plot_ly(tab, x = ~x, y = ~Count, type = "box", showlegend = F) %>%
        layout(yaxis = list(title = "Count"),
               xaxis = list(title = input$featureInput1))

      p2 <- plot_ly(tab, x = ~y, y = ~Count, type = "box", showlegend = F) %>%
        layout(title = "Box plot for Benign cases",
               yaxis = list(title = "Count"),
               xaxis = list(title = input$featureInput2))

      subplot(p1, p2)
    }

  })

}

runApp(shinyApp(ui, server), launch.browser = TRUE)

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
